[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
pump_meteora = "9s5i8n2dJPFpbmt55N7zop2iu8FTQ9TQjUXmfpNnzZYs"

[programs.localnet]
pump_meteora = "9s5i8n2dJPFpbmt55N7zop2iu8FTQ9TQjUXmfpNnzZYs"

[programs.mainnet]
pump_meteora = "9s5i8n2dJPFpbmt55N7zop2iu8FTQ9TQjUXmfpNnzZYs"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "./keys/admin.json"

[scripts]
build = "rm -rf target && anchor build && mkdir -p target/deploy && cp ./keys/program/*.json ./target/deploy/pump_meteora-keypair.json"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
